### PR TITLE
Don't ask for password if token was given

### PR DESCRIPTION
**Pull request by b-me**
Connected with #48

### CODE REVIEW

**Comment by b-me** [comment]
Update readme

**Comment by b-me** [comment]
WIP

**Comment by b-me** [comment]
Done

**Comment by ffigiel** [comment]
is faker a new dependency? Please add it to `dev_requirements.txt`

**Comment by b-me** [comment]
We can drop it.
Faker is factory boy dependency, but we can freeze it.

**Comment by ffigiel** [comment]
Ok, pls do that

**Pull request merged**
