### PR TITLE
Use github3 instead of PyGithub

### PR DESCRIPTION
**Pull request by ffigiel**
Closs #49 :tada:

### CODE REVIEW

**Comment by ffigiel** [comment]
All that's left is to adapt tests to the new backend. Any volunteers? ;)

**Comment by lhaze** [comment]
Iff failures in tests are consequences of #60 bug, mark these tests with `pytest.mark.xfail` and leave it to #60.

**Comment by ffigiel** [comment]
Nope, the monkeypatching needs to be changed too.

**Comment by ffigiel** [comment]
This PR has been moved to #61 because this branch became a mess.

**Pull request closed without merging**
